services:
  # Web Service - Streamlit Dashboard
  - type: web
    name: air-quality-dashboard
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run render_dashboard.py --server.port $PORT --server.address 0.0.0.0"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: air-quality-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.11

databases:
  # PostgreSQL Database
  - name: air-quality-db
    databaseName: airquality
    user: airquality_user
    plan: free